services:
  - type: web
    name: high-dividend-stock-tool
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    plan: free
    envVars:
      - key: PYTHONIOENCODING
        value: utf-8
      - key: LANG
        value: C.UTF-8
